### ISSUE TITLE
Edge case handling of duplicate group names with target ES2025

### ISSUE THREAD

**Issue by slevithan** [slevithan/oniguruma-to-es#14]
Note: The following details don't matter when emulating Oniguruma as experienced via `vscode-oniguruma`. `oniguruma-to-es` already correctly emulates the subpattern match values and indices as returned by `vscode-oniguruma` (which are complex to get right for certain edge cases) since `vscode-oniguruma` (as of v2.0.1) returns subpattern matches by index only, not including group names.

---

Context: As part of emulation for duplicate group names, `oniguruma-to-es` strips duplicate group names from all but the first instance. This is necessary since JavaScript prior to ES2025 didn't support duplicate group names. When not using option `avoidSubclass`, `oniguruma-to-es` also transfers in (via handling in `EmulatedRegExp`) the matched subpattern values and indices on result arrays from later subroutines that reference the group. All of this matches Oniguruma's behavior and the behavior visible from Onigmo via rubular.com.

For example:

- `(?<n>.)(?<n>.)` matched against `ab` returns `a` as the value for group `n`/`1`, and `b` as the value for group `2`.
- `(?<n>.)\g<n>` matched against `ab` returns `b` as the value for group `n`, and has no second capturing group on match results.

Despite being correct, note that none of this is intuitive. In other regex flavors, the subpattern value/index for a duplicate group name is based on the *last participating* instance. And PCRE/Perl/Regex+ subroutines revert any capturing groups that are set during a subroutine call to their previous values after exiting the subroutine, so subroutines in these regex flavors don't replace captured values on match results.

Also note that this doesn't affect backreferenes *within* the regex. Once again, Oniguruma does something weird here and makes backreferences to duplicate group names match any of the values captured by participating groups with the duplicate name ("backreference multiplexing"), and uses different/complex handling related to subroutines (of course, since Oniguruma seems determined to make no edge cases intuitive or easy to emulate). `oniguruma-to-es` already emulates all of this correctly.

So, all of the above is already working correctly, despite being weird and complicated.

However, a potential issue arises with `oniguruma-to-es`'s special handling for duplicate group names with `target: 'ES2025'` (or `target: 'auto'` in environments that support ES2025 regex features). For ES2025, `oniguruma-to-es`'s behavior changes subtly to keep duplicate group names on the first instance *per alternation path* (since this special case of duplicate group names is no longer an error in JS as of ES2025). So e.g. `(?<n>a)(?<n>b)|(?<n>c)(?<n>d)` becomes `(?<n>a)(b)|(?<n>c)(d)`.

This is `oniguruma-to-es` trying to be smart and use the latest features of JS, but it might be introducing an edge case issue in terms of identically copying Oniguruma behavior.

I'm not yet certain, but it seems like the handling for `target: 'ES2025'` might not follow Oniguruma accurately. `vscode-oniguruma` doesn't include capture names for subpattern matches on results, so it doesn't matter there and I can't test there. However, rubular.com (which uses Onigmo, a fork of Oniguruma) shows the following results when matching `(?<n>a)(?<n>b)|(?<n>c)(?<n>d)` against `abcd`:

**Match 1**

```
n/1. a
2. b
3.
4.
```

**Match 2**

```
n/1.
2.
3. c
4. d
```

The **match 2** results above don't match the results that you'd get for match 2 from JS `RegExp` behavior when executing the regex generated by `oniguruma-to-es` with `target: 'ES2025'`:

```
1.
2.
n/3. c
4. d
```

JS's behavior for the match result of subpattern `n` is `'c'` instead of `undefined`, since it returns the captured value of the group `n` instance that actually *participated* in the match.

If rubular.com is indeed showing the behavior of Oniguruma (rather than something specific to Onigmo or rubular.com), this can be fixed by simply dropping `oniguruma-to-es`'s fancy handling of duplicate group names with `target: 'ES2025'`, and handling it the same as with earlier `target` values.

**Comment by tonco-miyazawa** [comment]
@slevithan
Rubular's "Match groups" seem wrong. https://rubular.com/r/adP02b0KO231c6
```
(?<n>a)(?<n>b)|(?<r>c)(?<r>d)
Test string: abcd
r b   # I think this is a bug.
```

[oniguruma/doc/RE#L420-L425](https://github.com/kkos/oniguruma/blob/c98766f14e98cf3db83aa63213dbd381ae47a19a/doc/RE#L420-L425)
>  When backreferencing with a name that is assigned to more than one groups,
  the last group with the name is checked first, if not matched then the
  previous one with the name, and so on, until there is a match.
\
  \* Backreference by number is forbidden if any named group is defined and
    ONIG_OPTION_CAPTURE_GROUP is not set.

The following are tests using `v6.9.10`. (Same result on the current `master branch`.)

`(?<n>x)(?<n>xx)\k<n>` matches "`xxxxx`". ( Matched pos `0` to pos `5`, not pos `0` to pos `4`.)
`(?<n>x)(?<n>xx)\k<n>` matches "`xxxx`". (However, [Rubular fails](https://rubular.com/r/scvs2uJvqpY6kN).)

`(?<n>x)(?<n>xx)\k<n>x` does not match "`xxxxx`". ( https://github.com/kkos/oniguruma/issues/252 )
Oniguruma owner(K.Kosako)'s comment:
>This is inevitable because backreferences to duplicate names are achieved by a different process than the usual alternations(|). Therefore, it is a specification.
Consider that once one of these matches is made, the other options are cut.

`(?<n>x)(?<n>xx)\k<n>\k<n>x` does not match "`xxxxxx`". (6 `x`'s)
`(?<n>x)(?<n>xx)\k<n>\k<n>x` does not match "`xxxxxxx`". (7 `x`'s)
`(?<n>x)(?<n>xx)\k<n>\k<n>x` matches "`xxxxxxxx`". (8 `x`'s)

Is there a test you'd like to try?

**Comment by slevithan** [comment]
Thank you for adding more details, @tonco-miyazawa!

> `(?<n>x)(?<n>xx)\k<n>` matches "`xxxxx`". ( Matched pos `0` to pos `5`, not pos `0` to pos `4`.)
> `(?<n>x)(?<n>xx)\k<n>` matches "`xxxx`". (However, [Rubular fails](https://rubular.com/r/scvs2uJvqpY6kN).)

This shows a bug in oniguruma-to-es, since the library currently converts `(?<n>x)(?<n>xx)\k<n>` to `(?<n>x)(xx)(?:\1|\2)`. It should be `(?<n>x)(xx)(?:\2|\1)`.

Note that the behavior of backreferences to *nonparticipating* capturing groups is a major difference between JavaScript and other regex flavors. In JavaScript, they match an empty string (in other words, they always match). In most flavors (including Oniguruma), they fail to match and force backtracking. In Oniguruma, they might also trigger backreference multiplexing, when referencing a group with a duplicate name (as you've described).

JavaScript's behavior means you can't just list backreference numbers in reverse order for all the groups with the same name. For example, if backreference `\k<n>` in `(?<n>a)\k<n>(?<n>b)` was converted to `(?:\2|\1)`, it would match `''`. In that position, `\2` matches `''` since capturing group 2 hasn't yet participated in the match.

oniguruma-to-es is already smart about this and tries to detect backreferences to nonparticipating groups. In cases where it's possible to identify, it converts them to `(?!)`; and, for backreference multiplexing, it leaves the group number out of the list of alternatives. For example, it currently converts `(?<n>)|(?<n>)(?<n>)\k<n>(?<n>)` to `(?<n>)|()()(?:\2|\3)()` (leaving out `\1` and `\4`). However, it should be `(?<n>)|()()(?:\3|\2)()`.

> `(?<n>x)(?<n>xx)\k<n>x` does not match "`xxxxx`". ( [kkos/oniguruma#252](https://github.com/kkos/oniguruma/issues/252) ) Oniguruma owner(K.Kosako)'s comment:
> 
> > This is inevitable because backreferences to duplicate names are achieved by a different process than the usual alternations(|). Therefore, it is a specification.
> > Consider that once one of these matches is made, the other options are cut.

Hm, can this be emulated by simply using an atomic group like `…(?>\2|\1)`? In JS (which lacks atomic groups), this could use `…(?:(?=(\2|\1))\3)`.

> Is there a test you'd like to try?

Thank you for offering!!

One thing that can't be tested in vscode-oniguruma is *named* subpattern match values, after a match has completed. vscode-oniguruma's match results only include subpattern matches by number.

So, it would be helpful to confirm what is the value of `name` in the match result (after the match completes; not for backreferences within the regex) with `(?<name>a)(?<name>b)` and `(?<name>a)|(?<name>b)`.

Since JS doesn't support duplicate group names, oniguruma-to-es converts these examples to `(?<name>a)(b)` and `(?<name>a)|(b)`. Although these match the same strings as the Oniguruma versions, I suspect they are not giving the same values for their result object's `.groups.name` property as Oniguruma does.

(In ECMAScript 2025, JS adds limited support for duplicate group names, but only if they are within mutually exclusive alternation paths.)

Note that oniguruma-to-es cannot simply switch which group keeps the duplicate name from the first to the last, since the last group (furthest to the right) with the name might not be the last to participate in any given match. oniguruma-to-es has an existing system (that it uses for subroutines) that allows it to use its `RegExp` subclass (`EmulatedRegExp`) to transfer the captured value from the last participating group in a set of groups to a particular capture slot, before returning match results. So, this system could be reused for the duplicate group name case. This would require using the subclass whenever a regex uses duplicate names. So far, I haven't bothered to add the extra complexity of using this system for duplicate group names, because it's not relevant for emulation with systems (like TextMate grammars) that use vscode-oniguruma, since vscode-oniguruma doesn't include named subpatterns in match results. But, if I can confirm that Oniguruma is giving different subpattern values for duplicate group names in match results, I should probably go ahead and follow its rules, even though it will matter to very few users.

---

By the way, @tonco-miyazawa, since your profile mentions that you use translation tools for reading English, I must say that your English when discussing complicated technical issues is spectacular. You're always great at explaining things clearly. Thank you! 😊

**Comment by tonco-miyazawa** [comment]
> Since JS doesn't support duplicate group names, oniguruma-to-es converts these examples to `(?<name>a)(b)` and `(?<name>a)|(b)`. 

Thank you for the explanation. I don't use JavaScript so I didn't know about them. `\k<name>` shouldn't have been discussed here, sorry.

Below are the results of running [oniguruma/sample/names.c](https://github.com/kkos/oniguruma/blob/master/sample/names.c) .

----------------------------------------------------------------
### /* [Default](https://github.com/kkos/oniguruma/blob/c98766f14e98cf3db83aa63213dbd381ae47a19a/sample/names.c#L36-L37) of `names.c` */

```
  static UChar* pattern = (UChar* )"(?<foo>a*)(?<bar>b*)(?<foo>c*)";
  static UChar* str = (UChar* )"aaabbbbcc";
```

Result:
```
number of names: 2
match at 0

foo (1): (0-3) 
foo (3): (7-9) *
bar (2): (3-7) *
```

Note: About '`*`' https://github.com/kkos/oniguruma/blob/c98766f14e98cf3db83aa63213dbd381ae47a19a/sample/names.c#L20

----------------------------------------------------------------
### /* `(?<name>a)(?<name>b)` */

```
  static UChar* pattern = (UChar* )"(?<name>a)(?<name>b)";
  static UChar* str = (UChar* )"ab";
```

```
number of names: 1
match at 0

name (1): (0-1) 
name (2): (1-2) *
```

----------------------------------------------------------------
### /* `(?<name>a)|(?<name>b)` */

```
  static UChar* pattern = (UChar* )"(?<name>a)|(?<name>b)";
  static UChar* str = (UChar* )"ab";
```

```
number of names: 1
match at 0

name (1): (0-1) *
name (2): (-1--1)
```

----------------------------------------------------------------

I'm new to `names.c` and don't know it very well yet. Could you let me know if you would like to do additional testing?

> Hm, can this be emulated by simply using an atomic group like …`(?>\2|\1)`? 

I'm not sure if it's okay to use an atomic group. Intuitively, this seems like it might cause problems, but in quick testing it didn't cause any issues. The following tests found no differences:

### Case 1.  `(?:(?<n>xx)|(?<n>x))\k<n>` and `(?:(xx)|(x))(?>\2|\1)`

/* Against "`xx`" */
```
match at 0
0: (0-2)
1: (-1--1)
2: (0-1)
```

/* Against "`xxxx`" */
```
match at 0
0: (0-4)
1: (0-2)
2: (-1--1)
```

### Case 2.  `(?<n>xx)(?<n>x)\k<n>` and `(xx)(x)(?>\2|\1)`

/* Against "`xxxxx`" */
```
match at 0
0: (0-4)
1: (0-2)
2: (2-3)
```

### Case 3.  `(?<n>xx)(?<n>x)??\k<n>` and `(xx)(x)??(?>\2|\1)`

/* Against "`xxxxx`" */
```
match at 0
0: (0-4)
1: (0-2)
2: (-1--1)
```

Can you tell me if there are any tests that you would expect to have different results?

> translation tools

I use `google translate`. Japanese to English translations are less accurate than English to Japanese translations. If you think any of my comments need to be edited, please let me know and I will fix it right away.

@slevithan It's a pleasure to meet such a great IT engineer as you. Of course, @RedCMD is also great! Thank you.

**Comment by slevithan** [comment]
> Result:
> 
> ```
> number of names: 2
> match at 0
> 
> foo (1): (0-3) 
> foo (3): (7-9) *
> bar (2): (3-7) *
> ```
> 
> Note: About '`*`' https://github.com/kkos/oniguruma/blob/c98766f14e98cf3db83aa63213dbd381ae47a19a/sample/names.c#L20

This is very helpful -- thank you. However, the native API for JS `RegExp` match results can only include one value for each group name, due to the shape of the match result object. These values are stored on the `match.groups` object. If you use flag `/d` to add subpattern indices to the result, the positions by name are stored on `match.indices.groups`.

So, do any Oniguruma APIs consider there to be only one (official) subpattern match for duplicate group names? If yes, I should probably emulate those results. If not, the current oniguruma-to-es behavior for named subpatterns on match results might be good enough, since there isn't something official to emulate. The current behavior is that e.g. `match.groups.name` will hold the value from the first capture named `name`, but that value can be changed based on matches by later-participating subroutines to that name.

Even if there isn't an official single value from Oniguruma, because of the "*"s you pointed out on results, it still feels like it might be better to change this behavior to adjust the subpattern value based on later-participating instances of duplicate group names. But in this case, it wouldn't be a *bug*.

> Case 3. `(?<n>xx)(?<n>x)??\k<n>` and `(xx)(x)??(?>\2|\1)`

This case will fail to match the same result in oniguruma-to-es (it will match `'xx'` instead of `'xxxx'`) because it is not possible to determine at compilation time whether a capturing group with a lazy, zero-minimum quantifier has participated in the match when it reaches the backreference. So, the `\k<n>` will be converted to the equivalent of `(?>\2|\1)` (instead of just `\1` like it would be if this was a case where nonparticipation could be detected), and in JavaScript the `\2` will match `''`. 😔

It is technically possible to specifically target this case to make it work, since we could determine that the group is nonparticipating 
 since (1) it has a zero-min, lazy quantifier, (2) it is immediately followed by a backreference to it (there's nothing in between to potentially force backtracking), and (3) there are no tokens after the backreference that could lead to backtracking. But, outside of test cases, people don't write patterns that would satisfy those conditions, so it wouldn't be very useful.

This situation is documented in the "Supported features" table in the readme:

> Backreferences | To nonparticipating groups
> ✔ Error if group to the right<sup>[4]</sup>
> ✔ Duplicate names (and subroutines) to the right not included in multiplex
> ✔ Fail to match (or don't include in multiplex) ancestor groups and groups in preceding alternation paths
> ❌ Some rare cases are indeterminable at compile time and use the JS behavior of matching an empty string

I don't believe it's possible to solve this in a generalized way using native JavaScript `RegExp`. And there is no alternative to using native `RegExp` unless you create your own compatible regex engine in JS (it which case it would be huge, comparatively slow, and have a new set of bugs).

Even though oniguruma-to-es is not able to detect all cases of capturing-group-nonparticipation, the fact that it solves this at all (for most cases, in fact!) already makes it totally unique in the JavaScript world. And this issue is not triggered by any of the ~55,000 real-world Oniguruma regexes used in TextMate grammars provided by Shiki.

> It's a pleasure to meet such a great IT engineer as you.

Same to you, regex brother! 😊

**Comment by slevithan** [comment]
Fixes for the backrefernece issues have been published in v4.2.0. Thank you for pointing them out!

We can continue the conversation here, but note that I've created the tracking issues #35 and #36.

**Comment by RedCMD** [comment]
could possibly duplicate (part of) the regex
is `(?<n>xx)(?<n>x)??\k<n>` the same as `(xx)\1|(xx)(x)(?>\2|\1)`?
capture groups will need re-aligning afterwards tho

**Comment by slevithan** [comment]
@RedCMD:

Tweak: Your `(xx)\1|(xx)(x)(?>\2|\1)` should be `(?<n>xx)\1|(xx)(x)(?>\3|\2)`.

That's creative thinking, but I'm quite skeptical it could be made to work in a generalized way, once you accounted for all Oniguruma features, plus everything else already going on with capturing groups under the hood (given the needs of JS emulation).

Consider:

- `(?<n>…)(?<n>…)??…\k<n>`
- `(?<n>…)(?<n>…)??\k<n>…`
- `(?<n>…)(?<n>…)??…\k<n>…`
- `(?<n>…)…(?<n>…)??…\k<n>`
- `(?<n>…)…(?<n>…)??\k<n>…`
- `(?<n>…)…(?<n>…)??…\k<n>…`

…For any possible values of `…`.

As one of the simpler complications that first comes to mind, what about `(?<n>a)(?<n>b)??(?<n>c)??\k<n>`? Now we have something like `(?<n>a)\1|(a)(b)(?>\3|\2)|(a)(b)(c)(?>\6|\5|\4)|(a)(c)(?>\8|\7)`.

You might see the problems already:

- It's not equivalent, since there's no reason to assume that the testing order should go from `(a)(b)` → `(a)(b)(c)` → `(a)(c)`. The appropriate match order would probably have to change dynamically based on backtracking, which isn't possible.
- This is a factorial explosion in length, which could easily become an attack vector similar to ReDoS.

And what about when some of the `(?<n>…)` captures contain `\k<n>`, assuming they appear after some earlier instances of `(?<n>…)` have already participated?

And I shudder to think about how it would complicate subroutine handling, which is already complicated enough in Oniguruma but is *wildly* complicated in oniguruma-to-es after all the hoops that are jumped through to emulate all of their edge cases using JS's limited native regex features. You might say that subroutines can't reference duplicate group names… but they can! Just indirectly (they can reference a group that contains a duplicate group name).

**Comment by slevithan** [comment]
PS: The core problem for this tangent (that JS backreferences to nonparticipating groups match an empty string) is one of the biggest mistakes in the design of JavaScript regexes. The original creator of JavaScript agrees with me on that. Also, if it wasn't for that issue, it would be straightforward to emulate conditionals. Alas. Here is a list I posted a while ago of what I think are the mistakes in the design of JS RegExp: https://x.com/slevithan/status/1873569223768773092

PPS: Sorry Oniguruma, but my list of design mistakes for you would be much longer. 😂

**Comment by slevithan** [comment]
> The next issue is this. Please create an issue.

From the Oniguruma docs:

> \* (?i) option has no effect on word types (\w, \p{Word}). However, if the word types are used within a character class, it is valid. But, this would only be a concern when word types are used with the (?W) option.

I don't quite understand this. I do understand that if you are trying to limit to only ASCII word characters in all circumstances with `(?W)`, you'd have to be careful to not let Unicode case folding for `i` allow matching `ſ` (U+017F) and `K` (U+212A). But that has nothing to do with character classes.

It looks like the actual issue you are referring to might be much more complicated than that, based on the other links you posted. I will have to look at them closely, later.

> > PPS: Sorry Oniguruma, but my list of design mistakes for you would be much longer. 😂
> 
> 🙇I'm sorry everyone.🙇‍♀️

😊 Oniguruma is still amazing, and a marvel of engineering! But it does make a lot of things more complicated and unintuitive than they need to be, in my opinion. Sometimes there are probably good reasons for this, sometimes there are important historical or compatibility reasons, but sometimes it didn't need to be that way.

**Comment by tonco-miyazawa** [comment]
Against "`\xc5\xbf`"

```
(?iW)\w          /* search fail */
(?iW)\p{Word}    /* search fail */
(?iW)[\w]        /* Matched (0-2) */
(?iW)[[:word:]]  /* Matched (0-2) */
```

[Oniguruma Owner(K.Kosako)'s comment:](https://github.com/kkos/oniguruma/issues/264#issuecomment-1166383458)

>I agree that it is odd that these four results do not match.
However, for word type, it is difficult to have exactly the same behavior because of the particular implementation method.
Therefore, only word type has a special specification for `IGNORECASE`. But if you are not using the `(?W)` option, you probably don't need to worry about it.

### Problems caused by optimization (perhaps)

`(?iW)[^\W]` will probably be treated as `(?iW)\w` due to optimization.
`(?iW)[[^\W]]` will probably be treated as `(?iW)[\w]` due to optimization.
So `(?iW)[^\W]` and `(?iW)[[^\W]]` behave differently.

### This problem goes beyond the scope of `(?W)`

Against "`ss`"

```
^(?i)\w$          /* search fail */
^(?i)[\w]$        /* Matched (0-2) */
```

### New problems with Quantifier(`*`, `+`, `{n,}`, etc..)

The fact that `(?i)[\w]` matches `"ss"` creates a new problem. Quantifier can cause a phenomenon similar to `ReDos`. ex. `(?i)[\w]+`.  Please see the comments below for more details. https://github.com/kkos/oniguruma/issues/290#issuecomment-1825555154 This issue is separate from the `(?i)\w` and `(?i)[\w]` issue. But you'll need to be careful.

### About the behavior of `(?i)[\w]` matching "`ss`"

This may be a new problem for `oniguruma-to-es`. I tried it and it didn't match in JavaScript. Addressing this issue will result in the Quantifier issues mentioned above.

> 😊 To be clear...

In particular, the `{m,n}` that @RedCMD pointed out is hard to notice.🙀 https://github.com/slevithan/oniguruma-to-es/issues/25

> I think Oniguruma is amazing, and a marvel of engineering!

That's true! Of course, the same goes for what you're making.😊

**Comment by slevithan** [comment]
> Against "`\xc5\xbf`"

Aha! I was confused when first looking at the links you shared because of the use of encoded bytes `\xc5\xbf` rather than code points `\x{c5}\x{bf}`. I wrote my last comment after looking up code points U+00C5 and U+00BF, and not understanding why they would alter behavior for `\w` and character classes. I now see that the reason is because you were actually referring to U+017F (`ſ`). 😊 You would probably think that, since I included support for encoded bytes `\x80`+ in the very first release of oniguruma-to-es, I would remember this Oniguruma-specific quirk. But apparently no.

> ```
> (?iW)\w          /* search fail */
> (?iW)\p{Word}    /* search fail */
> (?iW)[\w]        /* Matched (0-2) */
> (?iW)[[:word:]]  /* Matched (0-2) */
> ```
> 
> [Oniguruma Owner(K.Kosako)'s comment:](https://github.com/kkos/oniguruma/issues/264#issuecomment-1166383458)
> 
> > I agree that it is odd that these four results do not match.
> > However, for word type, it is difficult to have exactly the same behavior because of the particular implementation method.
> > Therefore, only word type has a special specification for `IGNORECASE`. But if you are not using the `(?W)` option, you probably don't need to worry about it.

That's very interesting. And it seems to cover exactly what I described in my last comment about how `\w` with flags `iW` (or `iP`) should not let Unicode case folding expand to `ſ` (U+017F) and `K` (U+212A). You're pointing out that it actually *should* expand if `\w`, `\p{Word}`, or `[:word:]` are used within a character class, due to a failure on Oniguruma's part to implement this consistently (due to the underlying complexity, as described by kkos).

I think this is best treated as an Oniguruma bug. kkos might not have acknowledged it as a bug (and even added a line about it in the readme), but in my opinion it is nevertheless a bug for `\w` and `[\w]` to behave inconsistently.

The current behavior for oniguruma-to-es with flags `iW` is that `\w`, `\p{Word}`, `[:word:]`, and `\b` (and their inversions) always use Unicode case folding and match `ſ` and `K`. In other words, they follow the behavior that Oniguruma uses within character classes.

Thinking about this some more, I think there is a clear, "correct" answer to what the behavior should be: it should work like oniguruma-to-es already does. That is because although flag `W` limits to ASCII, flag `i` applies Unicode case folding (unless using the "ignore-case is ASCII" whole-pattern modifier `(?I)`), so flag `i` expands the ASCII `\w` to include additional characters. For the record, that's also how JavaScript's ASCII-only `\w` works with Unicode-based flag `i`. And I believe the same is true for other regex flavors with ASCII `\w` and Unicode flag `i`.

Based on the above (and because oniguruma-to-es and oniguruma-parser intentionally do not reproduce Oniguruma bugs), I don't expect oniguruma-to-es to change its behavior for word characters with flags `iW`, unless `(?I)` is applied to the regex (`(?I)` isn't yet supported). However, I should document this behavior difference somewhere.

> ### Problems caused by optimization (perhaps)
> `(?iW)[^\W]` will probably be treated as `(?iW)\w` due to optimization.
> `(?iW)[[^\W]]` will probably be treated as `(?iW)[\w]` due to optimization.
> So `(?iW)[^\W]` and `(?iW)[[^\W]]` behave differently.

You're right! Note that the optimizer will change both `[^\W]` and `[[^\W]]` to `\w`, but indeed it might change `[[^\W]…]` to `[\w…]`. You can test it [here](https://slevithan.github.io/oniguruma-parser/demo/).

But I don't think anything needs to change for this. The difference in behavior is something I consider an Oniguruma bug (as described above), and it's an extremely rare bug. So rare that it will probably never be encountered in the wild, since it requires that all of the following conditions are met:

1. Using flag `W` or `P`.
2. Using flag `i`.
3. Using `\w` or similar outside of a character class (possibly as a result of the optimizer changing the regex).
4. Searching text that includes one of the extremely rare characters U+017F or U+212A (one of which is only used in historical writing, and the other is a deprecated Unicode character).

Aside: Currently, oniguruma-parser only supports flags `imx` within mode modifiers like `(?i)` and `(?m-x:)`. However, flags `imxDPSW` are supported when provided as a top-level option.

> ### This problem goes beyond the scope of `(?W)`
> Against "`ss`"
> 
> ```
> ^(?i)\w$          /* search fail */
> ^(?i)[\w]$        /* Matched (0-2) */
> ```

Unlike the above, this aspect is more likely to cause real problems. To clarify for other readers, in this case flag `W` is not used, and the issue is that Unicode case folding is resulting in `\w` (and more) being able to match two characters instead of one.

I will address this thorny issue in my next comment.

Aside: I'm familiar with the "ss" == "ß" issue within Oniguruma character classes, but I've been trying to forget about it so that I don't have to deal with it. 😂

But seriously, thank you for bringing it up.

**Comment by slevithan** [comment]
(In case you've already read them, note that I just edited both of my last two comments to hopefully make them clearer and to try to make my case a little better. 😊)

**Comment by slevithan** [comment]
(In case you've already read them, note that I just edited both of my last two comments to hopefully make them clearer and to try to make my case a little better. 😊)

> > ### Problems caused by optimization (perhaps)
> > [...]
> 
> [...] I don't think anything needs to change for this, at least for the specific issue of how flag `W`/`P` changes the meaning. As described above, the difference in behavior is something that I think is best thought of as an (extremely edge case) Oniguruma bug. The issue is so rare that it will probably never be encountered in the wild, since it requires that all of the following conditions are met:
> 
> 1. Using flag `W` or `P`.
> 2. Using flag `i`.
> 3. Using `\w` or similar outside of a character class (possibly as a result of the optimizer changing the regex).
> 4. Searching text that includes one of the extremely rare characters U+017F (only used in historical writing) or U+212A (a character only provided for compatibility with legacy encodings; the Unicode standard recommends against its use, favoring normal capital K U+004B).

Despite what I said above, it's probably best to fix this in the optimizer anyway.

That's because the separate issue that expands `ß` to `ss` (for example) *also* changes its behavior based on whether any set that includes `ß` (such as `\w`) appears within a character class. This issue, which is unrelated to flags `W` and `P`, is less rare.

Since there are many different sets that include `ß` (and other characters that trigger similar behavior), the easiest thing to do is probably to just never let the optimizer move `CharacterSet` nodes into or out of `CharacterClass` nodes. This will require (relatively simple) updates in a few different [optimization transforms](https://github.com/slevithan/oniguruma-parser/blob/main/src/optimizer/README.md#optimizations) including `alternationToClass`, `unwrapNegationWrappers`, and `unwrapUselessClasses`.

The result will be that both of these issues are resolved in the optimizer, and that the optimizer never changes Oniguruma behavior.

**Comment by RedCMD** [comment]
could add an option to ignore `(?i)\w` != `(?i)[\w]`
there are well over 500 grammars that have `(?i)[\w]`
https://github.com/search?q=path:*.tmlanguage*%20/\(\?i\).*?\[[^\]]*?\\w/

**Comment by slevithan** [comment]
Good idea. An option is worth thinking about. If it was optional, that would make it seem more reasonable to support these behaviors in oniguruma-to-es.

However, before making any changes (in the optimizer, oniguruma-to-es, or documentation) related to these last couple of issues, I'd like to see what kkos says in the issues I raised for them upstream: https://github.com/kkos/oniguruma/issues/349, https://github.com/kkos/oniguruma/issues/350, https://github.com/kkos/oniguruma/issues/351.

> here's a PR for extracting capture group names

Thanks for the reference.

For other readers: Even if the vscode-oniguruma team accepts that PR (it's been sitting for a long time), it won't help oniguruma-to-es directly since it will only affect vscode-oniguruma users (and presumably it won't affect TM grammars since they only use numbers). Also it seems pretty basic -- it only gives capture indices for each name. For any duplicate names, usually you'll want to know the last to participate in the match, so you'll have to loop over the values to manually figure that out.

But that gives me an idea about how to simplify the implementation in oniguruma-to-es for the same thing. 🙂

**Comment by slevithan** [comment]
Okay, the outcome of the discussions with kkos was pretty clear. These behaviors and their inconsistency were undesired and/or unintended. He was very willing to change the behaviors or make them non-default, but some changes would be very hard and might not be worth it, as a result of implementation details.

But then kkos made the sudden and very sad decision to archive the project. 😓 Oniguruma was always an incredibly ambitious project for a solo developer and it had an incredible 23 year run of development. So it's extremely sad to see it come to an end.

---

I've addressed this last set of issues via the following:

- oniguruma-to-es: Added footnotes to the "supported features" table for flags `i` and `W`:

> 8. When using flag `i`, in extremely rare cases Oniguruma can change the length of matches based on Unicode case conversion rules. The behavior isn't reproduced in this library because ① the rules are applied inconsistently (report) and ② Oniguruma planned to disable all case conversion length changes by default in future versions.
> 9. Combining flags `W` and `i` can result in edge case Oniguruma bugs (report) that aren't reproduced in this library.

- oniguruma-parser: Created issue [#25](https://github.com/slevithan/oniguruma-parser/issues/25).

**Comment by tonco-miyazawa** [comment]
@slevithan 
You and K. Kosako(Oniguruma Ower) have worked hard to make Oniguruma better. Many thanks to both of you.
I respect K. Kosako's decision.

## About Oniguruma

https://github.com/kkos/oniguruma/issues/351  is solved by https://github.com/kkos/oniguruma/commit/5d0506c66c4d3613912fa81d7d1b99f83dbea8e2 . In other words, The Quantifier issues mentioned above  is solved in the [fix_351_349 branch](https://github.com/kkos/oniguruma/tree/fix_351_349) . I think this is a great benefit to users.
And also, [Time-Limit](https://github.com/kkos/oniguruma/pull/348) and Unicode property `\pC`, `\pL`, `\pM`, `\pN`, `\pP`, `\pS`, `\pZ` have been added.
It would be a loss for Oniguruma users if these are not released.

That's why I use fix_351_349 branch. This is `Oniguruma v6.9.11` for me.
For https://github.com/kkos/oniguruma/issues/349, there is no problem as long as I do not use ignore-case.

--------------------

## About PHP
As @slevithan already knows (Thank you for giving me a ⭐), [I have written a way to test Oniguruma 6.9.10 with PHP 8.4.6](https://github.com/tonco-miyazawa/PHP_syntax_oniguruma) . If you are good at PHP, please give it a try.

--------------------

## About Oniguruma-To-ES

I have nothing more to point out. Thank you for your assistance. I learned a lot about Oniguruma from you, thank you.

**Comment by tonco-miyazawa** [comment]
> So the "🤯" did not mean I thought the result was wrong. It only meant I was surprised by the result.

I had misunderstood this. To me this emoji looks like a "nauseated face emoji".
I'm glad I understood your intentions. Thank you for your answer.
