### ISSUE TITLE
Does not work in Bun

### ISSUE THREAD

**Issue by devunt** [slevithan/oniguruma-to-es#2]
https://github.com/slevithan/oniguruma-to-es/blob/964fa4b9320bae1507fef823e890850bf3789ba2/src/generate.js#L453
https://github.com/slevithan/oniguruma-to-es/blob/964fa4b9320bae1507fef823e890850bf3789ba2/src/transform.js#L321

These 2 line, specifically where it uses `\x` with raw string template, makes `oniguruma-to-es` incompatible with Bun, due to this issue https://github.com/oven-sh/bun/issues/7540 on Bun's side.

Although this is Bun's fault, as `oniguruma-to-es` works well in latest Node.js, it would be great if this is fixed in `oniguruma-to-es` since it would takes a while to get fixed in their side. 

A simple fix would be using double backslash as a escape character instead of using `String.raw` in those 2 lines, when it comes to use `\x` and `String.raw` together.

**Comment by slevithan** [comment]
Thanks for the detailed report!

Fix published in v0.4.1.

**Comment by CrossScarDev** [comment]
This still doesn't work in bun. New error (when running Astro with command `bunx --bun astro dev --host`):
```
977 |     throw new Error(r2`\xNN above 7F unsupported in Oniguruma "${raw}"`);
                            ^
error: Syntax Error
    at ./node_modules/oniguruma-to-es/dist/index.mjs:977:23
```

**Comment by slevithan** [comment]
@CrossScarDev I can't repro, and that error message you highlighted last appeared in Oniguruma-To-ES v0.1.2. Please upgrade to the latest version of this library (or of Shiki, if that's where you're using it). Alternatively, upgrading to the latest version of Bun should also fix it.
